# Generated by Django 4.2.6 on 2023-11-05 23:48

import dag_storage.dag.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dags',
            fields=[
                ('uuid', models.CharField(default=dag_storage.dag.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dags',
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('uuid', models.CharField(default=dag_storage.dag.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dag.dags')),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('uuid', models.CharField(default=dag_storage.dag.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_from', to='dag.nodes')),
                ('node_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_to', to='dag.nodes')),
            ],
            options={
                'db_table': 'edges',
            },
        ),
    ]
